// quickstart/vue-ai/src/components/AiGenerator.vue
<template>
  <div class="ai-generator">
    <h1>AI Text Generator</h1>

    <form @submit.prevent="generateText" class="generator-form">
      <div class="form-group">
        <label for="prompt">Prompt:</label>
        <textarea
          id="prompt"
          v-model="form.prompt"
          :class="{ error: v$.prompt.$error }"
          placeholder="Enter your prompt here..."
        ></textarea>
        <span v-if="v$.prompt.$error" class="error-message">
          {{ v$.prompt.$errors[0].$message }}
        </span>
      </div>

      <div class="form-group">
        <label for="maxTokens">Max Tokens:</label>
        <input
          id="maxTokens"
          type="number"
          v-model.number="form.maxTokens"
          :class="{ error: v$.maxTokens.$error }"
          min="1"
          max="1000"
        />
        <span v-if="v$.maxTokens.$error" class="error-message">
          {{ v$.maxTokens.$errors[0].$message }}
        </span>
      </div>

      <button type="submit" :disabled="loading || v$.$invalid">
        {{ loading ? 'Generating...' : 'Generate Text' }}
      </button>
    </form>

    <div v-if="result" class="result">
      <h3>Generated Text:</h3>
      <p>{{ result.generatedText }}</p>
      <div class="metadata">
        <span>Tokens Used: {{ result.tokensUsed }}</span>
        <span>Confidence: {{ result.confidence }}</span>
      </div>
    </div>

    <div v-if="error" class="error">
      Error: {{ error }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed } from 'vue'
import { useVuelidate } from '@vuelidate/core'
import { required, minLength, maxLength, minValue, maxValue } from '@vuelidate/validators'
import { useAiStore } from '../stores/ai'

const aiStore = useAiStore()

const form = reactive({
  prompt: '',
  maxTokens: 100
})

const rules = computed(() => ({
  prompt: {
    required,
    minLength: minLength(1),
    maxLength: maxLength(1000)
  },
  maxTokens: {
    minValue: minValue(1),
    maxValue: maxValue(1000)
  }
}))

const v$ = useVuelidate(rules, form)

const loading = computed(() => aiStore.loading)
const result = computed(() => aiStore.result)
const error = computed(() => aiStore.error)

const generateText = async () => {
  const isValid = await v$.value.$validate()
  if (!isValid) return

  await aiStore.generateText(form)
}
</script>

<style scoped>
.ai-generator {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

.generator-form {
  display: flex;
  flex-direction: column;
  gap: 20px;
  margin-bottom: 30px;
}

.form-group {
  display: flex;
  flex-direction: column;
  text-align: left;
}

label {
  margin-bottom: 5px;
  font-weight: bold;
}

textarea, input {
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 16px;
}

textarea {
  min-height: 100px;
  resize: vertical;
}

.error {
  border-color: #e74c3c;
}

.error-message {
  color: #e74c3c;
  font-size: 14px;
  margin-top: 5px;
}

button {
  padding: 12px 24px;
  background-color: #3498db;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 16px;
  cursor: pointer;
  transition: background-color 0.3s;
}

button:hover:not(:disabled) {
  background-color: #2980b9;
}

button:disabled {
  background-color: #bdc3c7;
  cursor: not-allowed;
}

.result {
  text-align: left;
  padding: 20px;
  background-color: #f8f9fa;
  border-radius: 4px;
  margin-top: 20px;
}

.metadata {
  margin-top: 10px;
  font-size: 14px;
  color: #666;
}

.metadata span {
  margin-right: 20px;
}
</style>

// quickstart/react-native-ai/src/components/AiGenerator.tsx
import React from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, Alert } from 'react-native';
import { Formik } from 'formik';
import * as Yup from 'yup';
import { useDispatch, useSelector } from 'react-redux';
import { generateText, selectAiState } from '../stores/aiSlice';

const validationSchema = Yup.object().shape({
  prompt: Yup.string()
    .required('Prompt is required')
    .min(1, 'Prompt cannot be empty')
    .max(1000, 'Prompt cannot exceed 1000 characters'),
  maxTokens: Yup.number()
    .required('Max tokens is required')
    .min(1, 'Max tokens must be at least 1')
    .max(1000, 'Max tokens cannot exceed 1000'),
});

const AiGenerator: React.FC = () => {
  const dispatch = useDispatch();
  const { loading, result, error } = useSelector(selectAiState);

  const handleSubmit = (values: { prompt: string; maxTokens: number }) => {
    dispatch(generateText(values) as any);
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>AI Text Generator</Text>

      <Formik
        initialValues={{ prompt: '', maxTokens: 100 }}
        validationSchema={validationSchema}
        onSubmit={handleSubmit}
      >
        {({ handleChange, handleBlur, handleSubmit, values, errors, touched, isValid }) => (
          <View style={styles.form}>
            <View style={styles.inputGroup}>
              <Text style={styles.label}>Prompt:</Text>
              <TextInput
                style={[styles.textInput, touched.prompt && errors.prompt && styles.errorInput]}
                multiline
                numberOfLines={4}
                onChangeText={handleChange('prompt')}
                onBlur={handleBlur('prompt')}
                value={values.prompt}
                placeholder="Enter your prompt here..."
              />
              {touched.prompt && errors.prompt && (
                <Text style={styles.errorText}>{errors.prompt}</Text>
              )}
            </View>

            <View style={styles.inputGroup}>
              <Text style={styles.label}>Max Tokens:</Text>
              <TextInput
                style={[styles.numberInput, touched.maxTokens && errors.maxTokens && styles.errorInput]}
                keyboardType="numeric"
                onChangeText={handleChange('maxTokens')}
                onBlur={handleBlur('maxTokens')}
                value={values.maxTokens.toString()}
              />
              {touched.maxTokens && errors.maxTokens && (
                <Text style={styles.errorText}>{errors.maxTokens}</Text>
              )}
            </View>

            <TouchableOpacity
              style={[styles.button, (!isValid || loading) && styles.disabledButton]}
              onPress={() => handleSubmit()}
              disabled={!isValid || loading}
            >
              <Text style={styles.buttonText}>
                {loading ? 'Generating...' : 'Generate Text'}
              </Text>
            </TouchableOpacity>
          </View>
        )}
      </Formik>

      {result && (
        <View style={styles.result}>
          <Text style={styles.resultTitle}>Generated Text:</Text>
          <Text style={styles.resultText}>{result.generatedText}</Text>
          <View style={styles.metadata}>
            <Text>Tokens Used: {result.tokensUsed}</Text>
            <Text>Confidence: {result.confidence}</Text>
          </View>
        </View>
      )}

      {error && (
        <View style={styles.error}>
          <Text style={styles.errorText}>Error: {error}</Text>
        </View>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    width: '100%',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 30,
  },
  form: {
    width: '100%',
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    minHeight: 100,
    textAlignVertical: 'top',
  },
  numberInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
  },
  errorInput: {
    borderColor: '#e74c3c',
  },
  errorText: {
    color: '#e74c3c',
    fontSize: 14,
    marginTop: 5,
  },
  button: {
    backgroundColor: '#3498db',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  disabledButton: {
    backgroundColor: '#bdc3c7',
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  result: {
    marginTop: 30,
    padding: 20,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  resultText: {
    fontSize: 16,
    marginBottom: 10,
  },
  metadata: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
});

export default AiGenerator;
